### ISSUE TITLE
メンバ変数に配列を含むクラスにおいて、「不正なメモリアクセス」が発生します。

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#10]
下記のコードをコンパイルして実行すると、以下の例外が発生します。 
"An exception of '0xC0000005' occurred." (「不正なメモリアクセス」を示す例外コードです)
「917 # 1」「917 # 2」は表示されますが、その後の「917 # 3」が表示されません。
```
func main()
	var c: C :: #C
	class C()
		*func ctor()
			do me.arr :: [917]
			do cui@print(me.arr[0].toStr() ~ " # 1\n") {←表示される}
			do cui@print((me.arr[0] + 0).toStr() ~ " # 2\n") {←表示される}
			do cui@print((0 + me.arr[0]).toStr() ~ " # 3\n") {←表示されずに、例外が発生}
			;var x: int :: me.arr[0] {←同様に例外が発生するコードです。}
			;do me.arr[0] :: 917 {←これは問題なく動作します。}
			do cui@print("ok\n")
		end func

		var x1: int
		var x2: int
		var x3: int
		var x4: int
		var x5: int
		var x6: int
		var x7: int
		var x8: int
		var arr: []int
		{x1～x8のどれかを削除したり、arrの定義を先にしたり、intをboolに変えたりすると実行時エラーは出ませんでした。}
	end class
end func
```

assemble.cのAssembleExprArray関数内にある下記の行によって生成されるコードで'0xC0000005'が発生しているようです。
ListAdd(PackAsm->Asms, AsmCMP(ValReg(8, RegI[reg_i + 1]), ValMemS(8, ValReg(8, RegI[reg_i]), NULL, 0x08)));

ただし、上記の行はif (!Option->Rls)の中に書かれているので、リリースモードでは通らないですが、リリースモードでも「917 # 3」が表示されないので、問題点は他の箇所にもあるようです。

**Comment by kuina** [comment]
確認しますっ。

**Comment by kuina** [comment]
よくこのバグを発見してくださいましたねっ。
むしろ、今まで問題にならなったことが奇跡というべきでしょうか。
機械語生成に近い部分の不具合で、広域に渡って見直す必要がありそうです。

簡単に説明しますと、機械語中に記述される数値は効率化のためになるべくサイズを削っているのですが、
(例えば、0x00000003 を 0x03 にするなど)
unsignedのつもりで削っていた部分が特定の命令ではsignedに解釈されオーバーフローしていたようです。

機械語にはsigned/unsignedの型が無く、使い方によってsigned/unsignedが解釈されるため、
unsignedの128のつもりで 0x80 としていた部分が、signedの 0xFFFFFFFFFFFFFF80 と解釈されて
-128と扱われてエラーが発生していました。
修正します><

**Comment by kuina** [comment]
修正しましたっ。

全域を確認したところ、
実際に問題となりえるのはadd命令に直接数値を指定してunsignedのつもりで削った場合のみであることが判り、
そのような箇所は1箇所しかありませんでした。
挙げてくださったコードが動作することを、ご確認いただけますでしょうか。

**Comment by tatt61880** [comment]
修正ありがとうございます！
挙げたコードが問題なく動作することを確認しました。

不具合を発見した元のコードも動作しました。
最新のdraw@rectを利用して描画も上手くいったので、ここに公開しておきます。 :-)
QRコードを作成するKuinのコードです。 http://tatt.ch/kuin/qr.kn
(※仕様が固まっていないと言われている機能も使用していますが、仕様変更の際は遠慮なく…！)

クローズします。

**Comment by kuina** [comment]
すごいのです…！
わたしのほうではまだKuinで大規模なプログラムを動かしていないのですが、これほどのプログラムが動けば安心できますね！
一般公開の際には、Kuin公式サイトで紹介させていただく可能性があります。

**Comment by tatt61880** [comment]
私の書いたKuinのコードは「くいなちゃんライセンス ( http://kuina.ch/others/license )」としますので、ご自由にご利用ください！ :-)
