### ISSUE TITLE
Kuinの非同期処理(スレッド)について

### ISSUE THREAD

**Issue by haruo-wakakusa** [kuina/Kuin#100]
現在Kuin言語においてはスレッド処理が非推奨となっておりますが、その検討を行いたく。

**Comment by haruo-wakakusa** [comment]
とりあえず必要と感じた「アセットの非同期ローディング」については、現在Kuin言語に実装中のスレッドでも対応可能であると判断したので、そのプログラミング例を示しました。このプログラムに問題ないか精査していただきたく。
https://github.com/haruo-wakakusa/kuin_scene1

**Comment by haruo-wakakusa** [comment]
9/28に本リポジトリのほうを一部修正しております。ご注意ください。

**Comment by kuina** [comment]
ご指摘の通り、参照カウンタが同時にアクセスされなければ非同期処理が可能で、おそらく提示してくださったプログラムは正しく動作すると思います。
非同期処理はどういう形で実現させるのかはまだ迷っていて、"よく分かっている人" 以外に向けては、非同期を行う典型的な処理に関しては標準ライブラリ内で勝手に非同期を行う、という方針にするしかないのではと思ったりしています。

**Comment by haruo-wakakusa** [comment]
プログラムのほうをご確認いただきありがとうございます。

**Comment by haruo-wakakusa** [comment]
Kuin言語は初心者向けの言語であるので、非同期処理というのは一応使われうると思いますが、並列処理というのはあまり需要がないものと思います。もう少しリッチな言語であれば、スレッドプールを用意したりメッセージキューを使ったロックフリー（では多分ない）なプログラミングができる必要があると思いますが、私のほうでもあまり必要性は感じていないです。もし必要なのだとすればWebサーバーですが、それはKuinよりも優れた言語がたくさんあるので別途それらを利用するのがいいのかと思います。これはあくまで私見ですが、今の参照カウント方式から、並行参照カウント方式などに切り替えるのは得策ではないと思います。それは目立った機能追加がなされずにパフォーマンスだけが低下してしまうので。

ただ、Kuin言語はくいなちゃんのものなので、あくまでご参考までに。
