### ISSUE TITLE
forブロックでの変数の初期化

### ISSUE THREAD

**Issue by satonayu** [kuina/Kuin#101]
forブロック内で定義した変数がデフォルト値に初期化されないようです。

再現コード
```
func main()
	for(0, 3)
		var test: bit32
		do cui@print(test.toStr() ~ "\n")
		do test :: 0x12345678b32
	end for
end func
```

結果
```
0x00000000
0x12345678
0x12345678
0x12345678
```
ドキュメントに以下のように書いてありますので、これはバグになるのでしょうか？
> 「デフォルト値」とは、変数を定義して何も代入していないときに格納されている値のことです。

**Comment by kuina** [comment]
ああー、厳密な仕様としては、ローカル変数が作られるタイミングは「var」が書かれている行ではなく、その関数に入ったときに作成されるので、関数に入ったタイミングでデフォルト値で初期化され、それ以降に書き換えると書き換えた後の値が維持されてしまいます。
このあたりが分かりにくいため、ドキュメントに追記しておきます><

**Comment by satonayu** [comment]
なるほど、そういう動作だったのですね。
仕様理解しましたー！
ドキュメント修正よろしくです！
