### ISSUE TITLE
kuincl.exe でビルドに成功しているのにFailureが出力されるケース

### ISSUE THREAD

**Issue by reinforchu** [kuina/Kuin#103]
0xE9170006の例外を投げるコード書いていたら気づいたのですが、kuincl.exe が最後に出す「Success.」と「Failure.」の意味は単純にビルドに成功したか、しなかったかで合っていますか。
引数オプションで -r のリリースビルドを指定した場合、ビルドに成功しているのにもかかわらず、「Failure.」とプロンプトに出力されるケースを確認しました。
原因は、resディレクトリが存在しない場合にリリースビルドをした時、存在しないディレクトリに対してarchive(res.knd)しようとしてコケてるのではと推測しています。(存在確認をしていない？)
[Kuin言語仕様書11](http://kuina.ch/kuin/spec11)と照らし合わせると、本来は「Success.」と出るのが意図している挙動ではないかなと思われます。(-q を付けて Failure. なのでエラー・警告のはず)
引数なしのデバッグビルドをすると、「Success.」と出るので挙動に違いが見られます。
空の resディレクトリをmkdirしてからリリースビルドするとSuccess.になるので、resディレクトリの有無が関わっていると思われます。
サンプルの0010_networkでも `do cui@print("test")` だけのコードでも再現できます。
影響してそうなコードは恐らく、ここらへんかなっと。
[https://github.com/kuina/Kuin/blob/develop/src/kuincl/main.c#L199](https://github.com/kuina/Kuin/blob/develop/src/kuincl/main.c#L199)

<img width="920" alt="2018-10-07 04 07 14" src="https://user-images.githubusercontent.com/1451449/46575054-fda75e00-c9e8-11e8-951e-8bbf7f6e0899.png">

バイナリ: kuin_2018_09_17.zip
OS: Microsoft Windows [Version 10.0.17763.1] x64
MSVS: Microsoft Visual C++ 2017 [Version 15.8.6]

**Comment by kuina** [comment]
確認しますっ。

**Comment by kuina** [comment]
修正しました！　問題なければクローズして頂けたらと思います。
