### ISSUE TITLE
意味解析でエラー

### ISSUE THREAD

**Issue by satonayu** [kuina/Kuin#104]
去年作って互換性がなくなっていたコードを修正するため、エディタに表示されているエラーをすべて潰してコンパイルしたら、意味解析でエラーが発生しました。
仕様かどうか難しかったのですが念の為報告させていただきます。

ダイアログのメッセージは「予期せぬエラーです」
再現用に最小化したソースコードを添付します。

```
func main()
end func

func makeJsonT(data: []char): @Json
end func


class Json()
	var err: @JsonError
	
	+*func toStr(): []char
	end func
end class


class JsonError(@Json)
	+*func toStr(): []char
	end func
end class
```

たっとさんも少し確認してくれましたので、その時のツイッター会話もリンク貼っておきます。
[会話ログ](https://twitter.com/tatt61880/status/1048873646352023553)

**Comment by kuina** [comment]
確認しますっ。

**Comment by kuina** [comment]
メモ: super変数の解析時に親クラスの解析が完了していない模様。

**Comment by kuina** [comment]
ちょっぴり苦労しましたが、たぶん直りました！
問題なければクローズして頂けたらと思います。

**Comment by satonayu** [comment]
修正ありがとうございます！
次のリリース頑張ってください！
