### ISSUE TITLE
[要望] 塗りつぶされた多角形を描画する関数の実装

### ISSUE THREAD

**Issue by haruo-wakakusa** [kuina/Kuin#106]
drawライブラリに塗りつぶされた多角形を描画する関数、多分polygon関数と呼ぶのだと思うのですが、もし可能なら実装して欲しいです。自分のイメージとしては、
(in draw.kn)
+func polygon(points: []float, color: int)
end func
です。それとも、多角形の描画は三角形の描画に置き換えるのが定石であればそれでも構わないです。よろしくお願いします。

**Comment by kuina** [comment]
これは予定していたのですが、後回しになってしまっていたため 2018.10.17 に間に合わせてみます。
動的に頂点数が変わる描画は、DirectX10 以降ではそのままではできないため、あらかじめ多角形クラスを生成してからその draw メソッドで描画する感じになるかもしれません。

**Comment by haruo-wakakusa** [comment]
ほんとですか？ありがとうございます！

**Comment by kuina** [comment]
実装しました！ 2018.10.17 で入ります。
結局 draw@poly および draw@polyLine 関数で、クラスのインスタンスを作ることなく多角形が直接描画できるようにしました。
0002_draw_2d サンプルで使い方を示しました。
問題なければクローズして頂けたらと思います。

**Comment by haruo-wakakusa** [comment]
多角形が描画できることを確認させていただきました。素早いご対応ありがとうございます。
