### ISSUE TITLE
fileライブラリの一部の関数に相対パスを使用すると正常に動作しない

### ISSUE THREAD

**Issue by hima2nd** [kuina/Kuin#107]
makeDir
copyDir
copyFile
の3つの関数について、引数に相対パスを含むとfalseを返し動作に失敗します。
makeDirについては、当該ディレクトリが存在する場合削除のみが行われ生成は行われずfalseを返します。
同じパスを絶対パスで指定した場合は問題なく動作します。

動作テストには逆引き辞典7の例をそのまま使用しました。

**Comment by kuina** [comment]
確認しますっ。

**Comment by kuina** [comment]
ふーむ、makeDir は win32api の関数が相対パスを受け付けていない様子です。
copyDir と copyFile は、正しく動作していますが、カレントディレクトリを Kuin 側で書き換えてしまったのが問題でした。
修正していきます。

**Comment by kuina** [comment]
修正しました！ 2018.11.17 では正しく動作するはずです。
問題なければクローズして頂けたらと思います。

**Comment by hima2nd** [comment]
正常に動作する事を確認しました
対応ありがとうございます！
クローズしますね。
