### ISSUE TITLE
図形が描画される条件について

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#108]
下記のコードは黄色い背景に赤い円が描画されることを期待したコードなのですが描画されません。
描画されるようにしていただくことは可能でしょうか。

コメントアウトしている★の2行のいずれかを有効にした場合は期待通りに描画されます。
(◆1と◆2の間の行で★を実行すると描画されるようです。)
上記の要望が実現不可能な場合は、このように `do wnd@act()` を入れることで対処しようと思いますが、その場合、どのような条件で描画されるのかを詳しく知りたいです。

よろしくお願いします。
```
func main()
	var wndMain: wnd@Wnd :: wnd@makeWnd(null, %fix, 200, 200, "test")
	var drawMain: wnd@Draw :: wnd@makeDraw(wndMain, 0, 0, 200, 200, %scale, %scale, false)

	{◆1}

	;do wnd@act() {★}
	;do wnd@msgBox(wndMain, "message", "msgBox", %none, %ok) {★}

	do draw@clearColor(0xFFFFFF00) {背景色の設定}
	do draw@render(0)
	do draw@circle(100.0, 100.0, 100.0, 100.0, 0xFFFF0000) {円}

	{◆2}

	do draw@render(0)

	while(wnd@act())
	end while
end func
```

**Comment by kuina** [comment]
想定としてはこのコードで描画されるべきなので、原因を調査します。

**Comment by kuina** [comment]
憶測ですが、drawコントロールが作成されてから wnd@act() や wnd@msgBox() を呼ぶまでは、まだ描画可能な状態になっていないのではないかと思いました。(Windows の挙動として)
ひとまず、drawコントロールを生成したときに内部的に wnd@act() 相当の処理を行うようにしました。
問題なさそうであればクローズして頂けたらと思います。

**Comment by tatt61880** [comment]
ありがとうございます！
問題なさそうです。クローズします。
