### ISSUE TITLE
最後の行が、改行された空の行やコメントでないとコンパイルに失敗します

### ISSUE THREAD

**Issue by r-m0** [kuina/Kuin#11]
kuin_jan_12_2017で、

func main()[改行文字]
end func[改行文字]

とすると、EP0006というエラーが出て困惑しました。

func main()[改行文字]
end func[改行文字]
[改行文字]

だと問題なかったです。最後の[改行文字]をコメントに変えてみた場合も大丈夫でした。

**Comment by tatt61880** [comment]
試してみたところ、end funcの後に改行文字が1つあれば大丈夫でしたが、1つもなければEP0006になりました。
どこでエラーになっているかを追ってみました。
parse.cの 関数「ParseStatEnd」内で 「AssertNextChar(L'\n', True);」としている箇所があります。
AssertNextCharでNextCharErr(c, c2)が呼ばれて「EP0006」が発生しています。
NextCharErr関数の先頭で
```
	if(c == L'\n' && c2 == L'\0')
		return;
```
とすると良いかもしれません。（この変更により、エラーにすべき箇所を握りつぶしてしまわないか、未検証です。）

**Comment by r-m0** [comment]
確認ありがとうございます！私が伝えたかったのも、end funcの後に改行文字が一つもない時のエラーです。
なので、

```
func main()[改行文字]
end func
```

でしたね。間違って書いてしまってお恥ずかしい・・・。

**Comment by tatt61880** [comment]
すみません、【NextCharErr関数の先頭で
```
	if (c == L'\n' && c2 == L'\0')
		return;
```
とすると良いかもしれません。】と書きましたが、これはコンパイルが通るようにコンパイラの動作を変更する場合の話です。

POSIX的には、ファイルの末尾は改行と決まっているので(参考: "[UNIX]Text File / Line" http://d.hatena.ne.jp/odz/20070112/1168618030 )、「もしPOSIXを意識するのなら、ソースコードは改行で終わるように定めた方が良いのかも？」と思いました。
ただ、Windowsでは改行で終わっていないファイルを簡単に作れてしまいますし、コンパイルが通らないと混乱しやすいと思います。「コンパイルが通る方が親切なのかも？」とも思います。悩ましいですね…。

関連して、POSIXに従っているエディタでは1文字のみのソースコード(FizzBuzzなど用)を用意するのが難しい場合がある(参考: "最後に改行がないファイルが作れない" https://github.com/vim-jp/issues/issues/152 )という問題があります(別件としてIssue立てた方が良いでしょうか？)。

**Comment by kuina** [comment]
ご報告ありがとうございます。
Kuinとしては「ソースコードは必ずしも改行で終わる必要はない」という仕様にしていますので、コンパイラ側で対応しますっ。

**Comment by kuina** [comment]
改行なしで終わっても正しく扱われるはず…と思ってソースコードを確認したところ、単に変数名が間違っていました。
修正してパッケージを下記にアップロードしましたので、動作をご確認いただけますでしょうか。
http://kuina.ch/kuin_dev/kuin_jan_15_2017.zip

**Comment by tatt61880** [comment]
アップロードされたパッケージは試していないですが、最新のコードをコンパイルして、問題が解消されていることを確認しました。コードの修正内容にも納得です。

r-m0さん
確認して問題がなければクローズをお願いします。

**Comment by r-m0** [comment]
解決されているのを確認しました。お早い対応ありがとうございます。クローズします！
