### ISSUE TITLE
ウィンドウ生成時にonPaintが呼ばれない。

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#112]
以前は下記のコードで描画されていた円と背景が、ウィンドウ生成時に描画されません。
(ウィンドウを画面からはみ出させて再度画面内に移動させようとすると描画されます)

#108(図形が描画される条件について)を修正したときのコミット( f1c680511e049051755fd9584bb252d5826218d1 )が関係しているようです。
ご確認お願いします。
```
func main()
	var wndMain: wnd@Wnd :: wnd@makeWnd(null, %fix, 200, 200, "test")
	var drawMain: wnd@Draw :: wnd@makeDraw(wndMain, 0, 0, 200, 200, %scale, %scale, false)

	do draw@clearColor(0xFFFFFF00) {背景色の設定}
	do draw@render(0)

	do drawMain.onPaint :: @onPaint

	while(wnd@act())
	end while
end func

func onPaint(wnd: wnd@WndBase, width: int, height: int)
	do draw@circle(100.0, 100.0, 100.0, 100.0, 0xFFFF0000) {円}
	do draw@render(0)
end func
```

**Comment by kuina** [comment]
ふーむ…！

**Comment by haruo-wakakusa** [comment]
私は複数のウィンドウを生成したときなどに初回描画が行われない現象が発生するのでwnd@Draw.paintメソッドを呼び出したりしています。今のところそれで事足りているので対処法としてはそんなでもいいようには思います。（初心者の人はonPaint関数のなかにdbg@printをあてて、ほら２回呼び出されてるじゃないかとか言いそうですが…）

**Comment by ghost** [comment]
原因が、恐らくですが、分かりました。

まず、issue #108 についてですが、コミット f1c6805 を戻してコンパイルしたところ、

```
func main()
	var wndMain: wnd@Wnd :: wnd@makeWnd(null, %fix, 200, 200, "test")
	var drawMain: wnd@Draw :: wnd@makeDraw(wndMain, 0, 0, 200, 200, %scale, %scale, false)

	do draw@clearColor(0xFFFFFF00) {背景色の設定}
	do draw@render(0)
	do draw@circle(100.0, 100.0, 100.0, 100.0, 0xFFFF0000) {円}

	do draw@render(0)
	do lib@sleep(1000) {1秒スリープ}

	while(wnd@act())
	end while
end func
```

上のように描画直後にスリープさせると、描画自体は行われるがその後の`wnd@act`(ウィンドウメッセージの処理)で塗りつぶされていることが分かりました。

そこで、`WndProcDraw`のコードの`WM_PAINT`のところを確認しました。すると、`wnd@Draw.onPaint`が`null`の場合の処理がスタティックコントロールのウィンドウプロシージャに移譲されていることが判明しました。スタティックコントロールは(デフォルトでは)`WM_PAINT`を受け取った時にシステムカラーで塗りつぶすので、直前の描画が上書きされてしまいます。これが恐らく issue #108 の原因です。

コミット f1c6805 では、`wnd@makeDraw`の処理の中で Draw コントロール作成時の`WM_PAINT`を先に処理し、その上に`draw@render`で描画できるようにするという解決がなされていました。しかし、この場合、最初の`WM_PAINT`時点では`onPaint`は必ず`null`(未設定)なので、呼び出してもらえません。

`onPaint`に関数を設定する前に`WM_PAINT`を処理していることが、この issue の原因だと思われます。

これらを踏まえて修正した結果、issue #108 のコードもこの issue のコードも正常に動くようになったので、プルリクエストを送ろうと思います。

**Comment by tatt61880** [comment]
ありがとうございます。
問題なさそうなのでクローズします。:-)
