### ISSUE TITLE
include文をドキュメントに書いて欲しい

### ISSUE THREAD

**Issue by theoremoon** [kuina/Kuin#113]
Kuin には include 文が存在するようですが、[ドキュメント](http://kuina.ch/kuin/spec1) に詳しく書かれていなかったため見落としていました。言語仕様として固まっていないということでなければ、折をみて追加していただきたいです。

　ざっと探したところ、 **include** という文字列が現れるのは以下のページのみでした。

- http://kuina.ch/kuin/change_log
- http://kuina.ch/kuin/spec1
- http://kuina.ch/kuin/spec13

**Comment by kuina** [comment]
そういえば追加し忘れていました。追加します。

**Comment by tatt61880** [comment]
現在はドキュメントにinclude文に関する記述があるので、本issueはクローズできそうです。
https://kuina.ch/kuin/spec9

**Comment by theoremoon** [comment]
pingどうもです
