### ISSUE TITLE
dbg@print出力先の表示順序変更

### ISSUE THREAD

**Issue by haruo-wakakusa** [kuina/Kuin#116]
issue #114より
> Kuinエディタはデバッグ出力された文字列を受け取って表示してくれますが、新しく出力された文字列を最後尾に追加していました。
> しかしその度に表示欄のスクロールが先頭にリセットされて、追加された文字列が確認できませんでした。
>
> この問題点は以下の通り。
> ・Kuinエディタにアクティブウィンドウを切り替えてスクロールしなければならない。
> ・連続的に文字列を出力しているときに、その内容を一切確認できない事です。
> （連続的にスクロールがリセットされるので下に追加された文字列が見れない）
>
> しかし、wnd@EditMultiにはスクロール位置を操作する関数がありません。
> そこで、新しい行を先頭に作る仕様に変更したいです。

issueのリオープンです。dbg@printを実行したときにログ出力のカーソルが末尾に来るようにコード修正のほうをお願いいたします。以下のMSDNの記事が参考になると思います。

https://support.microsoft.com/ja-jp/help/109550/how-to-programatically-append-text-to-an-edit-control
https://docs.microsoft.com/en-us/windows/desktop/controls/em-setsel

**Comment by kuina** [comment]
こちら、完了していますのでクローズします。
