### ISSUE TITLE
lib@sleep関数のリスク

### ISSUE THREAD

**Issue by ghost** [kuina/Kuin#118]
lib@sleep関数の定義(src/lib_common/time.c)が

```c
EXPORT void sleep(S64 ms)
{
	Sleep((DWORD)ms);
}
```

となっていますが、msdnの[Sleep関数](https://msdn.microsoft.com/ja-jp/library/cc429358.aspx)には

> Sleep 関数と、ウィンドウを直接的または間接的に作成するコードを組み合わせて使う場合は、注意が必要です。1 つのスレッドがウィンドウを作成した場合、そのスレッドはそのウィンドウに関係するメッセージを処理しなければなりません。また、メッセージのブロードキャスト（同報送信）が発生した場合、システム内のすべてのウィンドウへそのメッセージが送信されます。無期限の遅延を指定して Sleep 関数を呼び出していた場合、このような現象が発生すると、システムはデッドロック状態に陥ります。ウィンドウを間接的に作成する 2 つの例として、DDE と COM の CoInitialize があります。そのため、ウィンドウを作成するスレッドでは、Sleep 関数ではなく、MsgWaitForMultipleObjects または MsgWaitForMultipleObjectsEx 関数を使ってください。

とあります。ウィンドウを生成するプログラムにおいて潜在的なリスクがあるようです。

**Comment by ghost** [comment]
ただ、[MsgWaitForMultipleObjects関数](https://msdn.microsoft.com/ja-jp/library/cc429261.aspx)はウィンドウのメッセージキューの存在を前提にしているようなので、CUIプログラムでは使えそうにありません。

かと言ってSleepとMsgWaitForMultipleObjectsを使い分けるというのは、DLL側からはおそらくウィンドウプログラムかCUIプログラムかを見分ける事ができないので困難だと思われます。

**Comment by ghost** [comment]
ごめんなさい。自己解決してしまいました。

よく見ると、システムがデッドロック状態に陥るリスクがあるのは

> **無期限の遅延を指定して** Sleep 関数を呼び出していた場合

で、無期限の遅延を指定するには引数をINFINITE(-1)にする必要があるようです。スレッドを無期限に中断することの需要はほとんどなさそうなので、この問題は単純に

```c
EXPORT void sleep(S64 ms)
{
	THROWDBG(ms < 0, 0xe9170006);
	Sleep((DWORD)ms);
}
```

として負の数を指定できないようにすれば良さそうです。

**Comment by kuina** [comment]
なるほど、ご指摘ありがとうございました。
ウインドウメッセージの処理が停止していると
その間に別スレッドからのメッセージが処理できずに復帰できなくなるということですね。
無期限でなくても Sleep している間はそういうリスクがありそうですし、
Sleep でなくてもループ処理で時間がかかっている間はそういうリスクがありそうです。

いずれにせよ、Kuin ドキュメントにもある通り
メッセージ処理 (Kuin でいう wnd@act()) は定期的に呼ばないと
ウインドウがフリーズしますので、
ウインドウを作りながら長期間 Sleep やループ処理させることはそもそも控えたほうが良く、
あえてそういうプログラムを書きたい場合はユーザの判断にお任せしたいと思います。
(ただし Sleep の INFINITE は対応を忘れていましたので、何かしら対応しておきます。)
