### ISSUE TITLE
float型の変数の代入結果

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#12]
下記のコードの出力結果で、yの値が変です。
```
func main()
	var x: float :: 1.0
	do cui@print("x = " ~ x.toStr() ~ "\n") {←この行をコメントアウトすると、なぜかyの値が正しくなります}

	var y: float :: x
	do cui@print("y = " ~ y.toStr() ~ "\n")

	var z: float :: x $ float
	do cui@print("z = " ~ z.toStr() ~ "\n")
end func
```

```
【出力結果】
x = 1
y = 6.36599e-314
z = 1
```

**Comment by tatt61880** [comment]
var y: float :: x + 0.0
や
var y: float :: x * 1.0
とした場合は問題ありませんでした。
問題があるのは、直接代入したときに限られるようです。

**Comment by kuina** [comment]
何ですって…確認しますっ。

**Comment by kuina** [comment]
修正しましたっ。
float変数を2項演算する際の重大な命令が抜けていました。

**Comment by tatt61880** [comment]
修正ありがとうございますっ！

挙げたコードが問題なく動作することを確認しました。
不具合を発見した元のコードも動作したので、ここに公開します♪
http://tatt.ch/kuin/mandelbrot.kn

クローズしますっ
