### ISSUE TITLE
[エディタ]選択範囲をスニペットに追加がすぐに反映されない

### ISSUE THREAD

**Issue by konosumi** [kuina/Kuin#121]
Kuinのエディタで「選択範囲をスニペットに追加」を使い、コードスニペットを追加したのですが。すぐに反映されないようです。

いちどスニペットを追加した後に、何らかのスニペットを追加すると反映されました。また、いちど追加したスニペットを削除する方法があれば、教えていただけると嬉しいです！

**Comment by kuina** [comment]
確認しますっ。
実験的に追加できるようにしただけで、削除の機能等はまだ用意できていないため、
便利そうであればちゃんとした機能に仕上げたいと思います。

**Comment by konosumi** [comment]
確認ありがとうございます。恐れ入りますー。
コードスニペットは削除できると便利なため、ご検討のほどよろしくお願いしますm(_ _)m

**Comment by kuina** [comment]
スニペットの機能を大幅に強化しました。
v.2019.9.17 に入りますっ。

**Comment by konosumi** [comment]
ありがとうございますm(_ _)m
