### ISSUE TITLE
複合代入演算子の左辺値の評価回数

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#126]
下記のコードで、関数「f()」が2回実行されます。
おそらく、`do arr[f()] :: arr[f()] + 1` と同じ処理になっているためだと思いますが、2回実行されることは非直感的だと感じました。
また、処理速度的にも1回だけ実行されるのが望ましいと思います。
```
func main()
	var arr: []int :: #[1]int
	do arr[f()] :+ 1
	func f(): int
		do cui@print("f()\n")
		ret 0
	end func
end func
```

**Comment by kuina** [comment]
おっと…そういう落とし穴がありましたか><
修正を検討します。

**Comment by ghost** [comment]
修正してみました。

**Comment by tatt61880** [comment]
修正ありがとうございます！
クローズします。
