### ISSUE TITLE
【Kuinエディタ】予期せぬエラー (do arr[null] :+ 1)

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#130]
issue #126 (「複合代入演算子の左辺値の評価回数」)の修正後、下記のコードをコンパイルすると `予期せぬエラー`が出るようになりました。
※コンパイルエラー `EA0050 配列の添字は「int」型でなければなりません。` になるコードです。
```
func main()
	var arr: []int :: #[1]int
	do arr[null] :+ 1
end func
```

`null` の代わりに `x` にすると、 `EA0000 識別子「x」の定義が見つかりません。` というコンパイルエラーになって、このときも `予期せぬエラー` になります。

**Comment by kuina** [comment]
修正しましたっ。

**Comment by tatt61880** [comment]
早速の修正ありがとうございます！
修正されていることを確認しました。
クローズします。
