### ISSUE TITLE
予期せぬエラー do f(

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#132]
下記のコードをコンパイルすると `予期せぬエラー` が発生するようになりました。
```
func main()
	do f(
end func
```
1週間前のコミット( ffb0251738f0a7d8fdcd83829101f63e00ec797d )が関係しているようです。

**Comment by kuina** [comment]
確認します。

**Comment by kuina** [comment]
修正しました！

**Comment by tatt61880** [comment]
ありがとうございます！
修正されていることを確認したのでクローズします。
