### ISSUE TITLE
空ファイルの仕様について

### ISSUE THREAD

**Issue by ghost** [kuina/Kuin#134]
現状では、空のファイルはメインのソースファイルかどうかに関わらず「Hello, world!」を出力するソースコードに置き換えられています (`q`・`f`・ `9`についても同様)。

---

例えば以下のようなプログラムでは、

main.kn (メインのソースファイル)
```
include hello_world
```

main.hello_world.kn (空のファイル)
```
```

メインのソースファイル main.kn は空でないのに、「Hello, world!」プログラムとしてコンパイルされてしまいます。

---

言語仕様を参照すると以下のように記述されています。

> 指定した.kn内に1文字も存在しなかった場合は「Hello, world!」を出力するプログラムになる。

「指定した.kn」はメインのソースファイルを指すのでしょうか、それともコンパイルされる全てのファイルが当てはまるのでしょうか。

**Comment by kuina** [comment]
考えたこともありませんでしたが、メイン以外のファイルが空のときに空でなくなるのは違和感があるので、そのうち修正します。

**Comment by kuina** [comment]
本件は修正しました。
