### ISSUE TITLE
Kuin Editorに行コピーや行切り取りが欲しい

### ISSUE THREAD

**Issue by theoremoon** [kuina/Kuin#136]
領域を選択してない状態のC-c, C-xが欲しいです。どこを見れば良いか教えていただければ自分で実装してみようかなとも思っています。

**Comment by kuina** [comment]
何も選択せずに C-c,C-x すると、一般的に行のコピー＆ペーストになるのですね。
Visual Studio や、手元のテキストエディタで確認できました。
あまりこの操作をしたことがありませんでしたが、便利そうなので私のほうで追加してみます。

**Comment by kuina** [comment]
本件はTattちゃん( @tatt61880 )によって修正されました。

**Comment by theoremoon** [comment]
修正ありがとうございます。サッと確認してissue closeできそうにないので代わりに確認していただいてcloseお願いして良いでしょうか
