### ISSUE TITLE
test/test_exe/test.exe が失敗します。

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#137]
以前の `assemble.c` でコメントアウトされていた `DbgBreak();` が 10e6fc3c0890ae0b0f4154e5a04ca4882aba3d1e でアンコメントされた影響で、 `test/test_exe/test.exe` が失敗するようになりました。
https://github.com/kuina/Kuin/blob/10e6fc3c0890ae0b0f4154e5a04ca4882aba3d1e/src/compiler/assemble.c#L1666

また、 `output0023.exe` の実行時に `File not found: d1006.knd` という実行時エラーが発生します。

ところで、 2c1d45cf7be03e140c4859c00c41593d68f23e38 で ` lib_cui/cui.c` に追加された `system("pause");` の影響だと思うのですが、 `test.exe` 実行時に何度もEnterを押す必要があって面倒です。こちらの改善も検討をお願いします。
https://github.com/kuina/Kuin/blob/2c1d45cf7be03e140c4859c00c41593d68f23e38/src/lib_cui/cui.c#L243-L245

**Comment by kuina** [comment]
DbgBreak(); は修正しておきます。
system("pause") のほうは、CUI のデバッグ実行時に勝手にコンソールが閉じないようにする対応で、
それまでは pause を行う .bat を作ってそこから exe を呼び出していたのですが、
それだとエラーが起こったときにブレークできなかったので exe 側に埋め込むようにしていました。
テストのときだけは確かに厄介なので、回避できないか検討してみますっ。

**Comment by tatt61880** [comment]
本件は問題が解消済みなのでクローズします！
（KuinInKuinのマージ時点で解消していたと思われます。）
ありがとうございました！
