### ISSUE TITLE
Kuinが読み込むDLLがさらにほかのDLLに依存している場合に正常に動作しない

### ISSUE THREAD

**Issue by pinfort** [kuina/Kuin#138]
https://github.com/pinfort/cpprest-kuin-bridge/blob/master/src/cpprest_kuin_bridge.cpp

KuinからHTTPアクセスを行うライブラリを作るため、DLLで機能を追加しようとしています。
このときに、作成されたDLLが以下のような状態のときは期待通りに動作します。
- ほかのライブラリ等への依存がない
- 依存ライブラリがそのDLLに静的リンク(.lib, .a)されている

しかし、以下のときは期待した動作が行われません。
- 依存ライブラリが動的リンク(.dll)されている。
もちろんdataフォルダに必要なdllをすべてコピーしました。

Kuin Editorでビルド後のファイルを開くと、依存のdllはdataフォルダ以下にコピーされているわけですが、この状態で.exeを実行するとエラー file not found: hogehoge.dll となります。
そこで、dataフォルダにあるDLLをすべて.exeと同じディレクトリにコピーし、exeを実行したところ、期待される出力が得られました。しかしこれにも問題があり、通常Kuinの成果物をcuiで実行すれば、最終行でpauseされるところ、これが行われないことがわかりました。また、詳細は不明ですが、タイミングによって実行時間に大きな差が生まれることもわかっています。

**Comment by pinfort** [comment]
リンク先のリポジトリはごちゃごちゃいじっているので、意図がわからないかもしれません。

**Comment by kuina** [comment]
わたしの理解が間違っているかもしれませんが、
Visual C++ 等で普通に外部 dll を動的リンクするプログラム (ここでは exe とします) を作ると、おそらくその exe と同じディレクトリに dll を置かないとエラーになり、また dll の名前を変更するとエラーになります。

Kuin では、内部的に Win32API の LoadLibrary 関数で動的に外部 dll を呼び出すようにしていて、そうすると任意のディレクトリの任意の名前・拡張子の dll が呼び出せるようになっています。
Kuin 標準の dll がすべて data フォルダ内に入っても動くのはこのためです。

外部 dll の動的リンクをすべて LoadLibrary 経由にすると解決するのではと思いますが、大変そうならワークアラウンドを考える必要がありますね…。

**Comment by pinfort** [comment]
なるほど。Win32APIを直接叩くようにしてみます。

**Comment by kuina** [comment]
また、Kuin エディタではデバッグ実行時に各 dll やリソースを逐一コピーしなくて済むように、
data フォルダのパスを書いた txt だけを exe の横に配置して、data フォルダから dll やリソースを読むようにしていました。
Win32API を直接叩く場合は、dll のパスはその txt 内のパスを利用すると良いかもしれません。

**Comment by pinfort** [comment]
なるほど。そんな裏技？があったのですね

**Comment by pinfort** [comment]
LoadLibraryにすることで解決しそうなのでクローズします。
