### ISSUE TITLE
関数を変数にセットして、関数呼び出しをしようとすると Kuin が強制終了してしまう

### ISSUE THREAD

**Issue by sutefu7** [kuina/Kuin#139]
・環境
Kuin Programming Language 2019.9.17

・現象の説明
以下のコードを入力しようとする際、`f(1, 2)` の閉じかっこを書いたタイミングで Kuin が強制終了してしまいます。

    func globalAdd(a: int, b: int): int
    	ret a + b
    end func
    
    func main()
    	var f: func<(int, int): int> :: @globalAdd
    	var x: int :: f(1, 2)
    end func

※一文字ずつ手打ちすると強制終了しますが、メモ帳などにあらかじめ書いておいて、Kuin にコピペすると問題無しですし実行もできます。次の行に`do cui@print("\{x}\n")` と書けば `3` と問題なく表示もされます。

**Comment by kuina** [comment]
確認しますっ。

**Comment by tatt61880** [comment]
本件、「v.2020.5.17」で修正されているように思います。

**Comment by sutefu7** [comment]
現象が出なくなったことを確認しました！
ありがとうございました。closeします。
