### ISSUE TITLE
クラス定義時、初回だけ Shiftキー＋セミコロンキー（'+'の入力）を2回押さないと'+'が入力されない現象

### ISSUE THREAD

**Issue by sutefu7** [kuina/Kuin#140]
・環境
Kuin Programming Language 2019.9.17

・現象の説明
例えば、`class Aaa()`と手打ちしてEnterキーを押すことで、次の行のインデントされた位置にカーソルが移動します（`end class`も自動入力されます）。
この状態で、public なメンバー変数を定義しようとして、'+' を入力しようとしても何も反応がありません。再度`Shiftキー＋セミコロンキー`を押すことで'+'が入力されるようになります。

関数も同様に初回だけ、'+' が入力されず2回目の入力で'+'が入力されますが、関数からの公開メンバー変数は、仕様的にも運用的にもやらないので影響無し？だと思います。

    class Aaa()
    	
    end class
 
    func f()
    	
    end func

・対処方法？
2回 Shift + セミコロンキーを押せばいいだけなので、影響度（小）というか我慢すればいいか、くらいかなと思いました。

**Comment by kuina** [comment]
確認しますっ。

**Comment by kuina** [comment]
本件はTattちゃん( @tatt61880 )によって修正されました。

**Comment by sutefu7** [comment]
Kuin Programming Language 2021.9.17

上記環境で直っていることを確認しました！
ご対応ありがとうございました！
