### ISSUE TITLE
サンプルコード(0013_collision_and_particles)が構文エラーになり、動作確認できない

### ISSUE THREAD

**Issue by sutefu7** [kuina/Kuin#143]
以下のサンプルコードを読み込んだタイミングで構文エラーとなります。
多分古い仕様のままで、新しい draw.kn に対応していないです。

kuin_2019_09_17/samples/0013_collision_and_particles/main.kn

    ; Collision and Particles Sample (C)Kuina-chan
    
    func main()
    	
    	～省略～
    	
    	var particle: draw@Particle :: draw@makeParticle() {★EA0047: 10個の引数を受け取る関数呼び出しに1個の引数が指定されました。～省略～}
    	do particle.lifespan :: 30 {★EA0051: 公開されていないメンバ「lifespan」を参照しました。}
    	do particle.color2 :: 0x00FFFFFF {★EA0052: 参照先のメンバ「color2」が存在しません。}
    	var texParticle: draw@Tex :: draw@makeTex("res/tex_particle.png")
    	
    	～省略～
    	
    end func

**Comment by kuina** [comment]
おっと…><

**Comment by sutefu7** [comment]
「kuin_2020_06_27」のバージョンで直っていることを確認しました！
ありがとうございました。

**Comment by kuina** [comment]
こちらこそ、ご報告ありがとうございました！
