### ISSUE TITLE
Unicodeエスケープ

### ISSUE THREAD

**Issue by hisuie08** [kuina/Kuin#145]
Webアプリケーションをいじっているものです。WebAPIを叩いてjsonの情報を取得、解析させたいのですが、帰ってくるjson文字列の中にUnicodeエスケープを含むことがあって詰まってしまいました。
例えば「=」が「\u003d」のように帰ってくるのです。
この場合kuinではエスケープに用いる文字は大文字でないとエラーEP0057が出てしまうようだったので「\u003d」ではなく「\U003D」にしなければいけないと考えたのですが、正規表現で置換をさせようとしたところ置換の定義の段階でEP0057...
これ、どうすると良いでしょうか。

**Comment by tatt61880** [comment]
情報が不足しているのでエスパーして回答しますが、おそらく、エスケープシーケンスに関するミスがあるのだと思います。
```
func main()
	var str: []char :: "\\u0001\\u0002"
	var regex: regex@Regex :: regex@makeRegex("\\\\u")
	do cui@print(str ~ "\n")
	do str :: regex.replace(str, "\\\\U", true)
	do cui@print(str ~ "\n")
end func
```
これを実行したら
```
\u0001\u0002
\U0001\U0002
```
となります。
こういう置換をしたかったということで合っているでしょうか？

**Comment by kuina** [comment]
Kuinの仕様としては、\u は小文字で、続く16進数は大文字で書く必要があります。(いろいろ理由がありまして…)
その点は大丈夫でしょうか。

**Comment by hisuie08** [comment]
お二方返信ありがとうございます。
えっと、状況としては
WebAPIを叩いたときに得られるjsonが一部Unicodeエスケープシーケンスにされていて、それを通常文字列に治す処理の引数にとったときEP0057が出ました。
\uが小文字なのは問題なかったのですが、その後に続く16進数が小文字であったため、そのままの形では処理以前にそもそも受け付けてくれないようでした。
エスケープを無視するRAW文字列にして、エスケープシーケンスの16進数小文字の部分を大文字に正規表現で置換というのも考えたのですが触れ始めたばかりでやり方が分からず…
この場合kuin外部で、受け付けられるフォーマットに変換して渡してやる必要がありますか？

**Comment by tatt61880** [comment]
```
func main()
	var str: []char :: "a\\u003db\\u002ac\\u002bd"
	do cui@print("Before: \{str}\n")
	for i(0, 255)
		do str :: str.replace("\\u00\{i.toStrFmt("02x")}", [i $ char])
	end for
	do cui@print("After: \{str}\n")
end func
```
上記のコードを「コンパイル＆実行」すると下記の出力が表示されます。
```
Before: a\u003db\u002ac\u002bd
After: a=b*c+d
```
やりたいことはこれに近いですか？

**Comment by hisuie08** [comment]
はい。大まかにはそうです。
WebAPIから返ってくる文字列(var strに入る文字列)は\が1本だった、つまり"a\u003db\u002ac\u002bd"のようになっていたので、文字列を渡した時点で「16進数が大文字という規則に反しているUnicodeエスケープシーケンス」と判断されたものと思われます。

**Comment by tatt61880** [comment]
> WebAPIから返ってくる文字列(var strに入る文字列)は\が1本だった、

それはつまり、 `do cui@print(str)` で出力すると
`a\u003db\u002ac\u002bd` のように表示されるということではないですか？
その場合は、私の書いた下記の処理で `str` を目的の形に置換できるはずです。
```
	for i(0, 255)
		do str :: str.replace("\\u00\{i.toStrFmt("02x")}", [i $ char])
	end for
```
※上記のコードは「\uxxxx」が「\u00ff」より小さな場合です。 \u0100～\uffff も含む場合は別の方法を考える必要があります。

そうではない場合、
`do cui@print(str)` でエラーが発生しますか？
それとも `str` に代入する段階でエラーが発生しますか？

WebAPIから文字列を取得する処理を含め、状況を具体的なコードで示していただくと解決に繋がりやすいと思います。

**Comment by kuina** [comment]
(エスケープシーケンスはコンパイル時に解決するものだと思っていましたが、
実行時にエスケープシーケンスが働くケースはあるのでしたっけ…)

**Comment by youkidearitai** [comment]
これは次のような話ではないでしょうか？

1. WebAPIをJSONで取得（ここでは`"a\u003db\u002ac\u002bd"`としましょう）
2. 1で取得したJSONを静的なファイルに保存
3. Kuinエディタ上で`"a\u003db\u002ac\u002bd"`を貼り付けたらEP0057
4. なので、正規表現で`"a\u003db\u002ac\u002bd"`のエスケープシーケンスを大文字にしたい

だとすると、仰っている「正規表現で置換」はKuinエディタ上の「正規表現を使用する」ですかね？

そうだとすればこのようにできます。

検索する文字列に`\\u([0-9a-d]{4})`
置換後の文字列に`\\u\U\1`

![kuin-regex-replace](https://user-images.githubusercontent.com/305368/77254561-14a54300-6ca5-11ea-81dc-619f45be6c9c.png)

と入力して置換してみてください。
違っていたらごめんなさい

**Comment by hisuie08** [comment]
youkidearitaiさんの示していただいた状況です。
教えていただいたとおりに正規表現置換を実行したところエラーが消えて期待通りの結果「a=b*c+d」が出力されました。

挙動は望むものになったのでこれをkuinで書こうとして以下のコードになりました

```main.kn
func main()
	var path: []char :: file@exeDir()
	var handle: file@Reader :: file@makeReader(path ~ "text_file.txt")
	var s: []char :: handle.readStr()
	var str: []char :: s.replace("\\u([0-9a-d]{4})", "\\u\U\1")
	do cui@print(str)
end func
```

自分のディレクトリと同じところにあるtext_file.txt(a\u003db\u002ac\u002bdが書かれている)の中身を読み込んで置換することを期待したのですが、
[5,56]EP0007が出てしまいました。。。

**Comment by tatt61880** [comment]
解説は困難ですが、とりあえずこれでいかがですか？
(もっと簡単な方法もあるような気がします。)
```
func main()
	var path: []char :: file@exeDir()
	var handle: file@Reader :: file@makeReader(path ~ "text_file.txt")
	var str: []char :: handle.readStr()
	
	var re: regex@Regex :: regex@makeRegex("\\\\u[\\da-f]{4,4}")
	assert(re <>& null)
	var m: [][][]char :: re.findAll(&, str)
	if(m <>& null)
		for i(0, ^m - 1)
			do m[i][0][0] :: '0'
			do m[i][0][1] :: 'x'
			var num: int :: m[i][0].toInt(&)
			do m[i][0][0] :: '\\'
			do m[i][0][1] :: 'u'
			do str :: str.replace(m[i][0], [num $ char])
		end for
	end if
	do cui@print(str ~ "\n")
end func
```

↓ text_file.txtの中身を `a\u003db\u002ac\u002bd\u3042\u3044\u3046` とした場合の実行結果。
```
a=b*c+dあいう
```

**Comment by hisuie08** [comment]
できました！
ほかのunicodeエスケープシーケンスを代入しても動作することを確認できました。
ありがとうございます！
総じて返信おそくなってしまってすみません。皆様本当にありがとうございました！
