### ISSUE TITLE
【要望】出力を flush する関数の追加

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#146]
競技プログラミングで「リアクティブ形式」の問題( 例: https://yukicoder.me/problems/no/246 )を解く際に、標準出力の flush が必要になります。
追加の検討をお願いします。

**Comment by kuina** [comment]
はーいっ。

**Comment by kuina** [comment]
追加しましたっ。
仕様として問題なければ KuinInKuin のほうにも追加しておきます。

**Comment by tatt61880** [comment]
早速の対応ありがとうございます！
`cui@flush`, `file@Writer.flush` いずれも試して問題ないことを確認しました。

クローズします。
