### ISSUE TITLE
【ドキュメント】toStrFmt の書式の「符号」の説明文:「正なら」→「0以上なら」

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#148]
Kuinの組み込みメソッド( https://kuina.ch/kuin/spec8 )の toStrFmt の書式の表において、「符号」の説明に3回出てくる「正なら」はすべて「0以上なら」あるいは「非負なら」が正しいと思います。

![image](https://user-images.githubusercontent.com/2398152/80563031-9dda3300-8a24-11ea-97f2-c5ff6733b639.png)

**Comment by kuina** [comment]
ありがとうございます、修正しました！

**Comment by tatt61880** [comment]
修正ありがとうございます。クローズします。
