### ISSUE TITLE
予約語「env」の動作が言語仕様の説明文と異なります。

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#151]
[Kuin言語仕様11 コンパイラとIDE](https://kuina.ch/kuin/spec11) には
`指定した値は、プログラム中で「env」定数として[]char型で参照できます。 例えば「-e exe」と指定した場合、プログラム中に「env」と書くと「"exe"」の値が取得できます。`
と書かれていますが、そうなっていないようです。

「env」の仕様が変更されたのでしょうか？

下記のコードはコンパイルエラーとなります。
```
func main()
	do cui@print("\{env}\n")
end func
```

下記のコードはコンパイルエラーにはならないものの、env("exe")は空文字列になっているようです。(【】と表示されます。)
```
func main()
	do cui@print("【\{env("exe")}】\n")
end func
```

おそらくこれが原因で、build/test.bat が失敗します。
下記のエラーメッセージが出ます。
`0x0001000E: [\test: 1839, 9]文字「(」が記述されるべき箇所に、不正な文字「<」が記述されました。`

build/test_data/test.kn の 1839行目は以下のようになっています。
```
	if(env <> "web")
```

**Comment by kuina** [comment]
あ、すみません。 envの仕様が変わりました。
これまで「env」と書いていた箇所は、「env("e")」と書くことで同等となります。
またコンパイルオプションの「-x」の仕様も拡張しました。
「-x hoge=piyo」というふうに、=で繋げてキーと値が指定でき、「env("hoge")」とすることで "piyo" が取得できます。
「-x hoge」の場合、「env("hoge")」は "true" となります。
「env("e")」は特殊で、「-e」で指定した値が取得できます。
この仕様変更・拡張により、ユーザが任意のコンパイル時分岐が書けるようになりました。
テストは修正します><

**Comment by tatt61880** [comment]
`build/test_data/test.kn` の修正ありがとうございました！

https://kuina.ch/kuin/spec11 に `指定した値は、プログラム中で「env」定数として[]char型で参照できます。 例えば「-e exe」と指定した場合、プログラム中に「env」と書くと「"exe"」の値が取得できます。` という記述が残っています。こちらも修正していただくことは可能でしょうか。

現在 https://kuina.ch/kuin/download からダウンロードできる kuin_2021_04_17.zip に同梱されている kuin.exe で、
下記コードを実行環境「CUI」でビルドして "exe" が出力されることを確認しました。
```
func main()
	do cui@print("\{env("e")}\n")
end func
```

**Comment by tatt61880** [comment]
ドキュメントの修正ありがとうございました！
クローズします。
