### ISSUE TITLE
【ドキュメント】エスケープシーケンス関連の表示上の問題

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#158]
細かいですが、2点気付いたので報告します。

#### `cui@delimiter`
> 初期状態では、区切り文字は改行と半角スペースとカンマ([' ', ' ', ','])に設定されています。

#### `cui@print`
> 自動で改行は行われないため、改行したい場合は「 」を付加してください。

#### `file@Reader.delimiter`
> file@Readerクラスのインスタンスが生成されたときに、区切り文字は改行と半角スペースとカンマ([' ', ' ', ','])に設定されています。

#### `file@Writer.writeStr`
> 自動で改行は行われないため、改行したい場合は「 」を付加してください。

## ② \\ が \\\\ になっています。
https://kuina.ch/kuin/spec13
> 文字リテラルや文字列リテラル中にタブ文字は記述できません。 エスケープシーケンス「\\\\t」を代用してください。

> 文字リテラルや文字列リテラル中では改行できません。 エスケープシーケンス「\\\\n」を代用してください。

> 識別子に正しくない形式で「\\\\」が記述されました。

> 不正な形式のエスケープシーケンス「\\\\文字」が記述されました。

> 文字コード表記は「\\\\u」に続いて、数字または大文字アルファベットで4桁の16進数を記述しなければなりません。

**Comment by kuina** [comment]
おや…。

**Comment by kuina** [comment]
多分修正できたと思います！

**Comment by kuina** [comment]
(2) の修正がまだでした。

**Comment by kuina** [comment]
(2) も修正しました！

**Comment by tatt61880** [comment]
ありがとうございます！
修正されていることを確認しました！クローズします！
