### ISSUE TITLE
【要望】Kuin Editorの[コンパイル&実行]を押したときにプログラムにコマンドライン引数を渡す機能が欲しい

### ISSUE THREAD

**Issue by scrwnl** [kuina/Kuin#159]
Kuin Editorで`lib@cmdLine()`を使い[コンパイル&実行]を押した時にエラーが出てしまいます。
そこで、文字入力ダイアログでコマンドライン引数を渡す方法が欲しいです。

**Comment by kuina** [comment]
ご要望ありがとうございます！
> Kuin Editorでlib@cmdLine()を使い[コンパイル&実行]を押した時にエラーが出てしまいます。

エラーとはどのような内容でしょうか。もし lib@cmdLine() の挙動が仕様に沿っていなければ、修正したいと思います。
差し支えなければ、最低限のソースコードを貼って頂けると確認できそうです。
> そこで、文字入力ダイアログでコマンドライン引数を渡す方法が欲しいです。

確かにエディタからコマンドライン引数を指定できたほうが良いですね、
文字入力ダイアログにするかどうかも含め、検討します。

**Comment by ujsr** [comment]
すみません。エラーの件は私の勘違いでタイプミスしていました。

**Comment by scrwnl** [comment]
```
func main()
	var cmdline: [][]char :: lib@cmdLine()
	do cui@print(cmdline[0])
end func
```
を[コンパイル&実行]で実行すると
`0xE9170002`が出てしまいます。
リリースビルドでは問題ありません。

**Comment by kuina** [comment]
なるほど…、確認します。

**Comment by kuina** [comment]
エラーに関しては、コマンドライン引数が1つも無いときには lib@cmdLine() は空配列を返すため、
[0]にアクセスして要素外アクセス(0xE9170002)の例外が発生することは仕様通りでした。

```
func main()
	var cmdline: [][]char :: lib@cmdLine()
	if(^cmdline > 0)
		do cui@print(cmdline[0])
	end if
end func
```
のように、要素数が0より大きいことをチェックする必要があります。

エディタからコマンドライン引数を追加する件は、別途対応を進めています。

**Comment by kuina** [comment]
エディタにコマンドラインが指定できる機能を追加しました！
v.2021.08.17 に入る予定です。

**Comment by scrwnl** [comment]
ありがとうございます。クローズします。
