### ISSUE TITLE
[]char型を除く参照型のリテラルが定数と認識されない

### ISSUE THREAD

**Issue by hima2nd** [kuina/Kuin#16]
以下のようなコードでコンパイルすると[]char型以外の変数でEA0014エラーが発生します。

```
var c : []char :: [ 'a' ,'b' ,'c' ]
var f : []float :: [ 1.1 ,2.2 ,3.3 ]
var i : []int :: [ 1 ,2 ,3 ]
var b : []bool :: [ true ,true ]
var b8 : []bit8 :: [ 1b8, 2b8 ]
var b16 : []bit16 :: [ 1b16 , 2b16 ]
var b32 : []bit32 :: [ 1b32 , 2b32 ]
var b64 : []bit64 :: [ 1b64 , 2b64 ]

var cc : [][]char :: [ "abc" ,"def" ,"ghi" ]
var fu : func<()> :: @test

func test()
end func

func main()
end func
```

エラー内容
[Error] EA0014: グローバル変数「f」の値はコンパイル時に定数にできる値でなければなりません。
[Error] EA0014: グローバル変数「i」の値はコンパイル時に定数にできる値でなければなりません。
[Error] EA0014: グローバル変数「b」の値はコンパイル時に定数にできる値でなければなりません。
[Error] EA0014: グローバル変数「b8」の値はコンパイル時に定数にできる値でなければなりません。
[Error] EA0014: グローバル変数「b16」の値はコンパイル時に定数にできる値でなければなりません。
[Error] EA0014: グローバル変数「b32」の値はコンパイル時に定数にできる値でなければなりません。
[Error] EA0014: グローバル変数「b64」の値はコンパイル時に定数にできる値でなければなりません。
[Error] EA0014: グローバル変数「cc」の値はコンパイル時に定数にできる値でなければなりません。
[Error] EA0014: グローバル変数「fu」の値はコンパイル時に定数にできる値でなければなりません。

**Comment by kuina** [comment]
「コンパイル時に定数にできる値」というのが何を指すかについてですが、実は文字列以外の配列は定数とみなさない仕様になっていました。
ご指摘くださるまで失念していましたので、ドキュメントのほうに明記したいと思います。 ご報告ありがとうございましたっ。

**Comment by hima2nd** [comment]
確認ありがとうございます。
仕様と言うことで納得しました。
クローズしますね。

**Comment by kuina** [comment]
ドキュメントに追記しましたっ。
http://kuina.ch/kuin/c4
