### ISSUE TITLE
【Kuinエディタ】「コンパイル＆実行」の動作異常

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#165]
9898e90ceccad71dbaf83b4778d4738a94ebee44 のコミット以後、Kuinエディタで「コンパイル＆実行」した際に通常の動作をしません。
例えば `func main()` のように `f` から始まっているコードの場合、FizzBuzz (_preset02.kn) になります。

以下の (1), (2) が合わさってこの現象が起きているのではないかと思っています。

#### (1)
`src/compiler/parse.kn` の
`if(fileSize <= 2 & key = "\\" ~ \option@inputName)`
の箇所が、元々 `fileSize <= 1` だったのが `fileSize <= 2` になったこと。

#### (2)
`build/output/kuin_dll_main.cpp` の
```
		if (total >= 2)
			return 2; // A value of 2 or more is not distinguished.
```
の箇所。

### 修正方法？
```
		if (total >= 3)
			return 3; // A value of 3 or more is not distinguished.
```
のように `2` を `3` に変更して試してみたところ、とりあえず通常通り「コンパイル＆実行」できました。
この修正が適切か否かは判断できていません。

**Comment by kuina** [comment]
https://kuina.ch/kuin/spec11#053225627507
の仕様を、
> これらには、ファイルの末尾に改行を1つ加えることも許容される。 しかしそれ以上の改行やスペースなど他の文字を含めてはならない。

のように修正しました。

ちなみに、v.2021.8.17 からは、Linux、macOS、FreeBSD 向けにソースコード版を公開する予定です。

**Comment by tatt61880** [comment]
対応いただきありがとうございました。
クローズします。
