### ISSUE TITLE
【Kuinエディタ】インデントの自動整形が関連するCtrl-Z, Ctrl-Y後のカーソル位置

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#173]
インデントの自動整形が行われる変更を行った後、Ctrl-Z, Ctrl-Y すると、カーソル位置が元の位置と異なった位置になります。

以下、カーソル位置を★で表します。
### 例1
`block` と入力して改行すると
```
block
	★
end block
```
となり、Ctrl-Zすると
```
block★
```
となり、Ctrl-Yすると
```
block
	
end block★
```
となります。

## 例2
```
func main()
	block x
	end block
	
	block y
		
		
	end block
end func
```
で、 `func main()` の行頭でShift + ↓で 改行も含めて func main() 選択して削除すると
```
★block x
end block

block y


end block
end func
```
となり、Ctrl-Zすると
```
func main()
★	block x
	end block
	
	block y
		
		
	end block
end func
```
となり、Ctrl-Yすると
```
block x
end block

block y
	
	
end block★
end func
```
となります。

この動作は「行コピー/行切り取り」の動作確認中に気づいたのですが、行コピー/行切り取りの実装前(v.2021.8.17以前)から同じ動作です。

個人的には今までにこれで困ったケースは特にないのですが、
例2でも示したようにカーソル位置が大幅に移動するケースがあるため、不便と感じる場合もありそうです。

**Comment by kuina** [comment]
なるほど…。
他のエディタでも、Undo→Redo でカーソル位置が元に戻るとは限らず、仕様から整理したほうがいいかもしれませんね。

**Comment by tatt61880** [comment]
#175 のマージありがとうございました！
クローズします！
