### ISSUE TITLE
main関数が存在しないファイルをコンパイルしようとすると、字句構文解析完了後に落ちます。

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#2]
src\compiler\analyze.cで、
		SAstFunc* main_func = SearchMain();
の後に、
		if(main_func == NULL)
		{
			Err(L"EAxxxx", 0); // main関数が存在しないエラー。※エラー番号はﾃｷﾄｰです。
			return result;
		}
という感じでチェックすると良さそうです。
EA0001のエラー【「main」関数の定義は「func main()」としなければなりません。】が一番近そうですが、新規のエラー番号を追加した方が良さそうです。

**Comment by kuina** [comment]
ﾋﾟﾎﾟｯ!　把握しました！

**Comment by kuina** [comment]
修正しました。 クローズします。

**Comment by kuina** [comment]
すみません。 issueを提起してくださった方が修正を確認してクローズする流れのほうが良かったかもしれません。
reopenしてみます。
修正が確認できましたら、クローズしてくださいっ。

**Comment by tatt61880** [comment]
素早い修正ありがとうございます。
kuincl.exeを更新し、修正されていることが確認できました。
クローズします。
