### ISSUE TITLE
Kuinコンパイラに対するテストに失敗する

### ISSUE THREAD

**Issue by shelaf** [kuina/Kuin#21]
test\correctにあるテスト結果の改行コードが全てLFになっているため、改行コードを変換せずにgit cloneすると、Kuinコンパイラに対するテストが全て失敗になる。
なお、改行コードを全てCRLFに変換してやればテストに成功する。

**Comment by kuina** [comment]
盲点でした><
対処しますっ。

**Comment by kuina** [comment]
修正しましたっ。
\r を読み飛ばすようにしました。

**Comment by kuina** [comment]
特に問題になっていないようですのでクローズします。
再発するようであれば再オープンしてくださいっ。
