### ISSUE TITLE
終了コードが指定できるようにする

### ISSUE THREAD

**Issue by kuina** [kuina/Kuin#22]
終了コードが指定できるようにしますっ。
func main(): int を許容するか、メソッドで実現するかは検討中です。

**Comment by kuina** [comment]
lib@retCode メソッドで終了コードが指定できるようになりました。
do lib@retCode(1)
と設定すると、終了時のコードが1になります。
このメソッドを呼んでも直ちに終了するわけではなく、単に終了時に返す値が設定されるだけで、また何度でも呼ぶことができます。

**Comment by kuina** [comment]
一応わたしの手元で指定した終了コードが返ってそうなことは確認できています。
本件Tattさんからの要望でしたが、もしよろしければ念のために動作確認等を行っていただけると助かりますっ。

**Comment by tatt61880** [comment]
対応ありがとうございます。
・指定した終了コードが帰ってくること
・直ちに終了するわけではないこと
・何度でも呼ぶことができること
を確認できました。
クローズをお願いします。

**Comment by kuina** [comment]
ご確認ありがとうございます！
ところで return code という呼ばれ方もありますが、exit code のほうがより一般的のようでしたので、
隙を見て lib@exitCode という名前に変更しておこうと思います。
ひとまずクローズしますっ。
