### ISSUE TITLE
listのポインタ情報がコピーされるケースとされないケースがあります。

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#23]
listをディープコピー演算子(##)でコピーした際、ポインタ情報がなくなります。
関数の戻り値としてコピーされたものに関しては、ポインタ情報が残っています。
toBinメソッドで取得されるバイナリにはポインタ情報が含まれないようです。
仕様でしょうか？
```
{
[実行結果]
listB.term() = false
listC.term() = true
printBin: 3 9 1 7
printBin: 3 9 1 7
listB.get():9
listC.get():【An exception of '0xC0000005' occurred.】
}

func main()
	var listB: list<int> :: f()
	var listC: list<int> :: ##listB
	;do listC.head() {この行を実行すると、実行時エラーは解消されます。必要でしょうか？}

	do cui@print("listB.term() = " ~ (listB.term() ?("true", "false")) ~ "\n")
	do cui@print("listC.term() = " ~ (listC.term() ?("true", "false")) ~ "\n")

	;toBinを利用して調べても、listBとlistCに差は見られません。
	do @printBin(listB.toBin())
	do @printBin(listC.toBin())

	do cui@print("listB.get():")
	do cui@print(listB.get().toStr() ~ "\n") {9}
	do cui@print("listC.get():")
	do cui@print(listC.get().toStr() ~ "\n") {実行時エラー【An exception of '0xC0000005' occurred.】}

	func f(): list<int>
		var listA: list<int> :: #list<int>
		do listA.add(9)
		do listA.add(1)
		do listA.add(7)
		do listA.head() {※}
		ret listA {この行を「ret listA」から「ret ##listA」に変更すると、listB.get()で実行時エラーが発生します。}
	end func
end func

func printBin(bin: []bit8)
	var x: int
	var pos: int
	do cui@print("printBin: ")
	while(pos < ^bin)
		do pos :: x.fromBin(bin, pos)
		do cui@print("\{x} ")
	end while
	do cui@print("\n")
end func
```

**Comment by kuina** [comment]
確認してみますっ。

**Comment by kuina** [comment]
ドキュメントにまだ書けていないので申し訳ないのですが、
ディープコピー演算子および、toBin & fromBin メソッドは、値のコピーだけを保証していて、
その他の情報　(この例のような list の走査ポインタや、同じインスタンスを参照していた場合の参照関係など)　はコピーされません。
その他の情報に関してはそれぞれ個別に仕様が定められ、list の走査ポインタは必ず term(初期状態) を指し、同じインスタンスを参照していた場合でもインスタンスは必ず独立したものが生成されます。
また細かいルールとして、参照がループしていてはならず(無限ループになる)、toBin & fromBin の場合は参照が null のものがあってもならない(これらはメソッドなのでnull.toBinを参照してアクセス例外が発生する)という制約があります。

ただし、listの走査ポインタに関しては、listのメンバ変数のように考えるとコピーしたほうが自然な気がしましたので、このissue上で修正したいと思いました。

**Comment by kuina** [comment]
よく考え直したところ、
.toBin & .fromBin メソッドは、やっぱりメソッドである点が間違いですので、nullであっても変換できるように演算子に変えたいと思います。
ただ、もう良い感じの記号が残っていないため悩んでいます…。

案:
var n: int
var bin: []bit8 :: n.toBin()
do n.fromBin(bin, 0)
というのを、
var n:int
var bin: []bit8 :: n $> []bit8
do n :: bin $< int
などと考えています。 必要な点としては、toBin のほうは必ず[]bit8型になるので型指定は不要ですが、
.fromBin のほうは型が定かではないため、明示的な指定が必要だということです。

**Comment by kuina** [comment]
このため、
n $> []bit8
は、
n $>
だけでも良く、オペランドを取らないのであれば単項演算子にして
$>n
としてもいいのですが、単項演算子が2文字なのは違和感があるので迷っている状況です…。

**Comment by kuina** [comment]
ちなみに、[]bit8.toBin() と []bit8.fromBin() は異なるデータを返す処理なため、
$> と $< のように演算子を区別する必要はあります。
同じデータを返すのであれば「$> []bit8」と「$> int」のような型の区別だけでいけたのですが><

**Comment by kuina** [comment]
思ったよりも変更が大規模で、苦労しているところです…峠は越えました。

**Comment by tatt61880** [comment]
お疲れ様ですっ。

> ちなみに、[]bit8.toBin() と []bit8.fromBin() は異なるデータを返す処理なため、
> $> と $< のように演算子を区別する必要はあります。
> 同じデータを返すのであれば「$> []bit8」と「$> int」のような型の区別だけでいけたのですが><

toBin演算子 や fromBin演算子 が どのような使われ方を想定しているのか気になりました。
もし、[]bin8型の変数に対して toBin演算子 が使われることがなければ、
・「c $> []bit8」の 「$>」はtoBin演算子
・「bin $> int」の「$>」はfromBin演算子
といった具合に判断するような仕様も可能だと思います。

例えば[]bin8型のメンバ変数を持つクラスのインスタンスに対して toBin演算子が使われた場合は、内部的には []bin8に対してtoBinが行われることになると思いますが、これに関してはtoBinとfromBinが同じ演算子かどうかは関係ないと思いました。

**Comment by kuina** [comment]
そうできたらシンプルになりそうですね。
ただ null の扱いが懸念点で、[]bit8 のインスタンスが null だった場合、null を表すバイナリ列を []bit8 で返すべきではないかと検討しているため、[]bit8.toBin が値と異なる値になってほしいケースがありそうです。
また異なる型に fromBin されることを防ぐために、toBin したバイナリ列に型情報も埋め込もうかとも検討していました。

ちなみに、思ったよりも時間がかかってしまいましたが、ほぼ実装作業は完了しつつあります。

**Comment by kuina** [comment]
型情報の埋め込みと listの走査ポインタの復元以外は実装できたのでpushしました。
インスタンスがnullでも復元できます。
listの走査ポインタの復元の実装に移ります。

**Comment by kuina** [comment]
ちなみに一番苦労したのは、クラスの $< (fromBin) をするときにインスタンスがnullのことを考慮すると、
インスタンスの型情報なしにどのクラスのfromBinの関数アドレスを呼ぶべきかを特定するところでした…。

**Comment by kuina** [comment]
listの走査ポインタが復元できるようになりました。
型チェックは今回は後回しにしようと思います。
一応予定していた機能は実装しましたので、ご確認いただけますでしょうかっ。

**Comment by tatt61880** [comment]
対応ありがとうございます！
`var listC: list<int> :: (listB $> []bit8) $< list<int>`
とした場合は問題なさそうです。

ディープコピーは未対応でしょうか？
`var listC: list<int> :: ##listB`
だと実行時エラーになりました。

(※横着してコードのタグで括らなかったために、`<int>`が表示されなかったため、修正しました。)

**Comment by kuina** [comment]
あっと…忘れていました。
ディープコピーも対応させますっ。

**Comment by kuina** [comment]
ディープコピーのlist走査ポインタのコピーに対応しました。

**Comment by tatt61880** [comment]
ありがとうございます！
修正されて、実行結果が想定通りになっていることを確認しましたっ
クローズしますっ
