### ISSUE TITLE
キャスト演算子に対するオペランドが異常な場合、字句構文解析完了後に落ちます。

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#25]
下記のコードのコンパイル時に、kuincl.exeが異常終了します。
```
; ※コンパイルエラーになるコードです。
; 2行とも ast == NULL の状態で「case L'$'」を通ります。
func main()
	var x: int :: $ int
	var y: int :: 1 + $ int
end func
```
状況としては、#24 の「2.0 ^ -1.0」で異常終了する件と似ている感じです。
parse.cの ParseExprCall関数内にある 「case L'$'」の箇所で、「if (ast == NULL) { Err(～); ～ }」の処理を追加すれば良いかもしれません。

**Comment by kuina** [comment]
確認しますっ。

**Comment by kuina** [comment]
単項演算子より優先順位が高い二項演算子のみで起きうる問題だと思いました。
おそらくこの修正で問題ないのではないかと思います。

**Comment by tatt61880** [comment]
修正ありがとうございます！
問題が解消されていることが確認できました！
クローズしますっ
