### ISSUE TITLE
【異常終了】メソッドのオーバーライド

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#26]
下記コードのコンパイル時に異常終了します。
また、+*を+に変更するとコンパイルは通って実行時にエラーになります。
```
func main()
	class C1()
		+func m(): int
			ret 111
		end func
	end class
	class C2(C1)
		+*func m(): int
			ret 222
		end func
	end class

	var c: C1 :: #C1
	var x: int :: (c $ C2).m()
	do cui@print("x=\{x}\n")
end func
```

**Comment by kuina** [comment]
確認しますっ。

**Comment by kuina** [comment]
修正しました。
キャスト演算子( $ C2 )で、型の意味解析が抜けており、C2クラスが解析されていませんでした。

**Comment by tatt61880** [comment]
ありがとうございます。コンパイル時の異常終了は解消しましたっ。
コンパイルによって生成されたexeを実行すると実行時エラーになるのですが、私が書いたコードは何か間違えているでしょうか？
(c $ C2)を (#C2)に変更すると、問題なく動作します。

**Comment by kuina** [comment]
C1からC2のキャストは、親から子クラスへのキャストになりますので、
型変換できないものとして例外が発生しているものと思います。
C2からC1へのキャストは可能です。

**Comment by kuina** [comment]
例外が発生したときにメッセージを出すようにする予定ですので、
今後は判りやすくなる予定です…><

**Comment by tatt61880** [comment]
ダウンキャストができない件、了解しました。
「C2からC1へのキャストは可能」とのことですが、下記のコードでも、キャストできない例外が発生します。
```
func main()
	class C1()
	end class
	class C2(C1)
	end class

	var c1: C1 :: ((#C2) $ C1)
	;var c2: C2 :: ((#C1) $ C2)
end func
```

**Comment by kuina** [comment]
あれ、本当ですね…テストでカバーしていたつもりでしたが漏れていたのですね、修正します><

**Comment by kuina** [comment]
ちょっと混乱してきたので仕様をまとめます:

- 子の型から親の型へのキャストは無条件に可。
- 子の型から親の型への代入(暗黙キャスト)は無条件に可。
- 親の型から子の型へのキャストは、インスタンスがその子(および孫etc)のものである限り可。
- 親の型から子の型への代入(暗黙キャスト)は無条件に不可。

このうち、無条件に可/不可のものはコンパイル時に判定していて、親から子へのキャストに限り、実行時に判定していました。
テストに追加しておきます。

**Comment by kuina** [comment]
修正しましたっ。
ずっと前に、クラスのキャストにはメインメモリを使わずレジスタだけで演算できるように最適化をしたのですが、そこにミスがありました。

**Comment by tatt61880** [comment]
ありがとうございます！
修正されていることを確認しました！
クローズしますっ
