### ISSUE TITLE
cui@print、cui@inputの文字コードについて

### ISSUE THREAD

**Issue by kuina** [kuina/Kuin#27]
現状UTF-16ですが、UTF-8のほうが良いかもしれません。
検討してみます。

**Comment by kuina** [comment]
Tattちゃんが修正してくださったのでクローズしますね。

**Comment by kuina** [comment]
あれ、cui@inputのほうはまだでしたっけ。

**Comment by tatt61880** [comment]
すみません、cui@inputはまだでした。
上記のように新しいプルリク( #71 )で対応しました。

**Comment by kuina** [comment]
ありがとうございます、確認しました！
クローズします。
