### ISSUE TITLE
Kuinエディタの雑多な不具合

### ISSUE THREAD

**Issue by kuina** [kuina/Kuin#31]
- マウススクロールに未対応
- マウスの横スクロールにも対応してほしい
- PageUp/PageDown
- タブの行頭を選択してタブを押すと、おかしな範囲選択になってしまう
- ~保存した後にSave Asすると、無視される~
- ~.knファイルを関連付けても開けない~
- Release Buildで書き込めないフォルダが指定されたときのエラーが解りにくい
- コンパイルエラーがたくさん出て解りにくいかも
- 単語単位で選択
- ~空のファイルを読み込むと動作が停止する~
- ファイルを変更したかどうかがわかりにくい

他、見つかるたびに追記していきます。

**Comment by kuina** [comment]
- 新規ファイルをCtrl+Sで保存するダイアログでキャンセルすると、カーソルの表示が行番号の領域まで左に行く(カーソルの位置自体は正常)

**Comment by tatt61880** [comment]
- [Compile & Run]で実行中のウィンドウを消さずに 再度[Compile & Run]を押したときのエラーメッセージがわかりにくいと思いました。

**Comment by hima2nd** [comment]
- テキストをドラッグで選択した際にスクロールバーが点滅します。
- ドラッグ時にテキストエディタの領域外に移動しボタンを離すと、領域内に戻った際にドラッグ状態が維持されたままになります。

**Comment by kuina** [comment]
みなさん、追記ありがとうございますっ。

- リリースビルドの生成先フォルダが空でなかった場合わかりにくい
- リリースビルドの生成先を開発用フォルダにすると、resフォルダが消えてしまう

**Comment by kuina** [comment]
Tatt さんの修正をマージしました。

**Comment by kuina** [comment]
~チルダで囲むと取り消し線になる模様。~
終わったタスクは取り消し線を引きます。

**Comment by nekketsuuu** [comment]
* [ ] こんな
* [ ] 感じで
* [x] チェックリストにする

と、issue リストでも[進捗が確認できるようになります](https://help.github.com/articles/about-task-lists/)。いかがでしょうか。

**Comment by kuina** [comment]
そんな機能が…！

**Comment by kuina** [comment]
一応ここで挙がった問題は修正完了していると思いますのでクローズします。
