### ISSUE TITLE
enum要素の型に関する意味解析時の異常終了

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#34]
```
func main()
	enum E
		a
	end enum
	switch(1)
	case %a
	end switch
end func
```
上記のコードをコンパイルすると、意味解析時に異常終了します。
（※異常終了しなかったとしても【EA0019: 「case」節の型が「switch」ブロックの条件式の型と一致しません。】というコンパイルエラーになるコードです。）

compiler/analyze.c の RebuildEnumElement という関数内にある、
	ASSERT(IsEnum(type));
で引っ掛けられています。

下記のコードでは異常終了せずに、コンパイルが通ります。
```
func main()
	enum E
		a
	end enum
	switch(1 $ E)
	case %a
	end switch
end func
```

**Comment by kuina** [comment]
Tattさんから頂いたコードをそのままコミットしました。
問題なければクローズしてくださいっ。

**Comment by tatt61880** [comment]
問題ありません。クローズしますっ
