### ISSUE TITLE
型が一致しないコンパイルエラー時の異常終了

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#38]
```
const a: int :: 1
const b: int :: @a + 0.0 {[Error] EA0056: 型が一致しません。}
func main()
	do cui@print(@b.toStr())
end func
```
上記のコードのコンパイル時にkuincl.exeが異常終了します。

https://github.com/kuina/Kuin/blob/f8950fcc34fa2a5a36f84a7a2087273a344f4e76/src/compiler/analyze.c#L2352
analyze.cの2352行目で「[Error] EA0056: 型が一致しません。」になり、
https://github.com/kuina/Kuin/blob/f8950fcc34fa2a5a36f84a7a2087273a344f4e76/src/compiler/analyze.c#L3731
同3731行目の「arg->Expr」がnullptrとなって「ハンドルされない例外」が発生します。

**Comment by kuina** [comment]
確認します！

**Comment by kuina** [comment]
本件、修正しました！

**Comment by tatt61880** [comment]
修正ありがとうございます！
異常終了しないことを確認しました。
クローズします。
