### ISSUE TITLE
「EA0048: 関数呼び出しの引数の型が異なります」で表示されるキャストされていないenum型の表示名が異常

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#46]
下記のコードをコンパイルしようとすると、 `[Error] EA0048: 関数呼び出しの引数の型が異なります。 1番目の引数で「int」を指定すべきところに「」が渡されました。` という変なエラーメッセージになります。

※「%e」の箇所を「%e $ E」とした場合は問題ありません。
```
func main()
	enum E
		e
	end enum
	func f(x: int)
	end func

	do f(%e)
end func
```

**Comment by kuina** [comment]
修正しました！

**Comment by tatt61880** [comment]
ありがとうございます！
修正されていることを確認したのでクローズしますっ
