### ISSUE TITLE
enumの「EA0056: 型が不正です。」に伴うkuincl.exeの異常終了。

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#48]
下記のコードのコンパイル時に、`[Error] EA0056: 型が不正です。` というコンパイルエラーが出た後に、kuincl.exeが異常終了します。(わざとコンパイルエラーを発生させようとして見つけた不具合です。)
```
func main()
	var e: E :: %a
	enum E
		a :: 0.0 + 0
	end enum
end func
```
analyze.cのRebuildEnumで例外がスローされています。

**Comment by tatt61880** [comment]
すみません、タイトルが適切ではなかったかもしれません。
エラーの種類に依らず、enumの定義でエラーが発生した場合に異常終了するようです。

例えば下記のコードのコンパイルでは、`EA0064: 演算がオーバーフローしました。`というエラーが発生した後、異常終了します。
```
func main()
	var e: E :: %a
	enum E
		a :: 9223372036854775807 + 1
	end enum
end func
```

他にも例えば下記のコードのコンパイルでは、`EA0039: 「null」は値比較できません。`というエラーが発生した後、異常終了します。
```
func main()
	var e: E :: %a
	enum E
		a :: null = null
	end enum
end func
```

**Comment by kuina** [comment]
確認しますっ。

**Comment by kuina** [comment]
修正しました。
上記 3 つのコードで異常終了しなくなることを確認しました。

**Comment by tatt61880** [comment]
ありがとうございます！
修正されていることを確認しました！クローズします。
