### ISSUE TITLE
「EA0056: 型が不正です。」に伴うkuincl.exeの異常終了。 

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#50]
下記のコードのコンパイル時に、`[Error] EA0056: 型が不正です。` というコンパイルエラーが出た後に、kuincl.exeが異常終了します。(わざとコンパイルエラーを発生させようとして見つけた不具合です。)
```
func main()
	var x: int :: %a
end func
```

**Comment by kuina** [comment]
修正しました！
また、戻り値にも同様の問題があり、ret %a などとするとエラーが発生しましたので同時に修正しました。

**Comment by tatt61880** [comment]
ありがとうございます！
修正されていることが確認できたのでクローズします！
