### ISSUE TITLE
regex@Regex.matchの第一引数のposが冗長

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#64]
`regex@Regex.match`の第一引数のposについて。
posは文字列全体がマッチしていたら必ず0になり、それ以外は-1になります。
文字列全体がマッチしているか否かは戻り値のnull判定で可能なので、posは冗長だと思いました。

**Comment by kuina** [comment]
あれ…直し忘れていましたか><

**Comment by kuina** [comment]
修正してみました。

**Comment by tatt61880** [comment]
対応ありがとうございます。
手元に動作確認ができる環境がないため、後日確認させていただきます。:-)

**Comment by tatt61880** [comment]
修正されていることを確認しました！
クローズします！
