### ISSUE TITLE
実行時定数とパラメータ付き列挙型

### ISSUE THREAD

**Issue by narumincho** [kuina/Kuin#67]
ラムダ式よりも実装してほしい、関数型言語の機能があります。
## 実行時定数
実行時定数です。コンパイル時定数ではないです。

    let 変数名 : 型名 = 値

これがあることによって、一度代入したものは変更することができなくなり、バグを防ぐことができます。letで定義されたものが上書きされているかいないかはコンパイル時に調べれば、実行時に普通のvarで定義したのと同じように扱ってもいいです。
#### letがない場合
    var x: int :: 5
    ～長いコード～
    ; xの上書き
    x :: 6
    ～長いコード～
    ;このxの値は何か知るために、スコープの範囲内すべてを見なければならない
    do cui@print(x.toStr())
#### letがある場合
    let x: int = 5
    ～長いコード～
    ;このxの値は何か知るためには、定義部分だけを見ればいい
    do cui@print(x.toStr())
また
    `let 変数名 : 型名 = 値`
か
    `let 変数名 : 型名 ::  値`
はどちらでもいいですが、数学の=との意味も合いますし、タイプ数も少ないので=の方が良いと思います。

## パラメータ付き列挙型
トランプの型を定義したいときにこうできれば便利

    func main()
        let heart5: @Trump = %normal(%hert, 5)
        switch(hert5)
        case %normal(%spade, 3)
            do cui@print("スペードの3")
        case %normal(_, 0 to 10 @ n)
            do cui@print("番号は10以下で\{n}")
        case %normal(_, n)
            do cui@print("番号は10より大きくて\{n}")
        case %joker
            do cui@print("ジョーカー")
        end switch
    end func
    
    enum Suit
        spade
        heart
        diamond
        club
    end enum

    enum Trump
        normal(Suit,int)
        joker
    end enum

#### パラメータ付き列挙型がなければ

    func main()
        var heart5: @Trump :: (#@Normal).set(%heart, 5)
        
        if(heart5 =$ @Normal)
            var n: @Normal ::heart5$@Normal
            if(n.suit = %spade & n.number=3)
                do cui@print("スペードの3")
            elif(0 <= n.number & n.number <= 10)
                do cui@print("番号は10以下で\{n.number}")
            else
                do cui@print("番号は10より大きくて\{n.number}")
            end if
        elif(heart5 =$ @Joker)
            do cui@print("ジョーカー")
        end if
    end func

    class Trump()
    end class

    class Normal(@Trump)
        +var suit: Suit
        +var number: int
        *func ctor()
            
        end func

        +func set(s:Suit, n:int): @Trump
            do me.suit :: s
            do me.number :: n
            ret me
        end func
        
        enum Suit
            spade
            heart
            diamond
            club
        end enum
    end class

    class Joker(@Trump)
    end class

**Comment by kuina** [comment]
参考になりますっ。

let のほうは C++ の const や Java の final に相当するものだと思いますが、
C# には無く、また無いためにうっかり代入して困ったという話を聞いたことがないので、
Kuin の言語仕様を複雑にするデメリットと天秤にかけると無くても支障はないかと思いました。

パラメータ付き列挙型は興味深いですね。
これは初めて見る機能で、いろいろと応用が広がるかもしれません。
実体が 8byte を超えるのでレジスタに代入できず、
処理速度がかなり落ちるという実装上の課題が多そうですが、勉強になります。
