### ISSUE TITLE
wnd@WndBase.getPosScrの名前

### ISSUE THREAD

**Issue by ghost** [kuina/Kuin#68]
`wnd@WndBase.getPosScr`の名前について、screenの略語としてscrを使っていますが、
・略語辞典に記載されていない
・scrから元の語がわかりづらい
ので、単語を略さない`wnd@WndBase.getPosScreen`のほうがよいと思いました。
いかがでしょうか。

**Comment by kuina** [comment]
検討してみます！

**Comment by kuina** [comment]
元々 Screen を Scr に略した背景としては、
Screenという単語の使用頻度が高いことと、
Windowsのスクリーンセーバーの拡張子が「*.scr」になっているところから
略す方針にしようと考えていました。

しかしScrから元の語が分かりづらいというのは一理ありますので迷うところですね。
略すのはやめましょうか。

**Comment by ghost** [comment]
拡張子はwindowsの三文字制限の名残みたいなものだと思うので、一般的にはあまり略されない単語だと思います
6文字は長すぎないし、vectorやmatrixほど使用頻度が高くないので、screenに変更しましょう

**Comment by narumincho** [comment]
私も、screenが良いと思います

**Comment by kuina** [comment]
はーい！

**Comment by kuina** [comment]
修正しました！
問題なければクローズしてください。

**Comment by ghost** [comment]
ありがとうございます。修正を確認しました。
クローズします。
