### ISSUE TITLE
複数行コメントと単一行コメントが入り交じっているケースに関して。

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#7]
;}
↑のような行はコンパイルエラーにならずに存在しうる行だと思います。
これを{}でネストした
{
;}
}
という3行は、3行ともコメントになるか、2行目までがコメントになるか、どちらでしょう？

もし2行目までがコメント扱いなら、途中に「;}」が含まれるような複数行をまとめてコメントアウトしたいときに面倒だと思いました。
仕様( http://kuina.ch/kuin/a10  )には、【複数行コメント、単一行コメント、charリテラル、[]charリテラルが入り混じっていたときは、先に出現するものから優先される。】と書かれているので、3行目までかなと思うのですが、現状は2行目までになっているようです。

**Comment by kuina** [comment]
修正しますっ。

**Comment by kuina** [comment]
修正しました。 ご確認頂けますでしょうかっ。

**Comment by tatt61880** [comment]
{
	;}
}
↑で修正されていることが確認できました。
↓はまだコンパイルエラー(【[Error] EP0009: コメント「{」に対応する「}」が存在しません。】)になるようです。
{
	;{
}
ご確認お願いします。

**Comment by kuina** [comment]
了解しましたっ。

**Comment by kuina** [comment]
修正しましたっ。

**Comment by tatt61880** [comment]
確認しました。
クローズします。
