### ISSUE TITLE
廃止されたエラーメッセージ

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#72]
言語仕様の変更により廃止されたと考えられる下記4つのエラーメッセージがドキュメント( http://kuina.ch/kuin/b13 「Kuinコンパイルエラーと警告」)に残っています。
- EP0008: ソースファイル中に全角スペースは記述できません。 エスケープシーケンス「\w」を代用してください。
- EP0053: 「ifdef」ブロックの条件に「dbg」「rls」以外の「%s」が記述されました。
- EA0026: 「foreach」ブロックで扱えない型の値が指定されました。
- EA0029: 「throw」文の例外メッセージは「[]char」型でなければなりません。

また、上記のエラーメッセージのうち、EP0008 以外は sys/msg.knd にも残っています。

誤解を招く恐れがあるため、廃止された旨が伝わるようにしておくと良いと思います。

**Comment by kuina** [comment]
了解ですっ。

**Comment by kuina** [comment]
修正しました。
ドキュメントは、他にもいろいろと変更があったため最新のエラーメッセージ内容に従って修正しました。

**Comment by tatt61880** [comment]
修正されていることを確認しました。
クローズします。

非常に些末ですが、 ドキュメントにおいて、EA0011-EA0013で`列挙型の要素`と書かれている箇所は、msg.kndに合わせるのであれば、`列挙型「列挙型名」の要素`かなと思います。それ以外の箇所はmsg.kndに合っているようです。:-)

**Comment by kuina** [comment]
> 列挙型「列挙型名」の要素かなと思います。

修正しました！
