### ISSUE TITLE
アルファの半透明の濃さがおかしい

### ISSUE THREAD

**Issue by kuina** [kuina/Kuin#76]

**Comment by kuina** [comment]
調査・修正したところ、アルファの半透明が想定よりも薄くなっていることが分かりました。
draw@makeFont の引数に、うっかり strong という引数を追加してしまいましたが、
修正したらやっぱり不要であることが分かりました。
たびたび引数を変えて申し訳ないですが、strong は削除しようと思います…><

それでアルファを修正したのですが、
結局、ペイントソフトや画像ビューアの見た目よりはアルファが薄くなってしまうことが分かりました。
これは、Kuinではリニア空間で計算しているためで、仕方がないものです。

簡単に説明しますと、みなさんが見ている画面は色が本来の色よりも暗く歪んでいるため、
ペイントソフトや画像ビューアで半透明のブレンドを行うと、
(アルファは歪んでいませんが)
歪んだ色同士の計算が行われて、本来とは違う色になってしまいます。
ただ、最終的に画面に表示するときに逆方向の歪みをかけているため、結果にはそれほど違和感は生じないという仕組みです。

しかしKuinや、他の多くの3Dゲームプログラムでは、
光などの計算を歪んだ色空間で行うと、物理学的に正しくない歪んだ結果になってしまうため、
計算途中は歪んでいない色空間(リニア空間といいます)に直してから計算しています。
このため、アルファも色も歪んでおらず、本来の色の計算が行われますが、
半透明部分がペイントソフトや画像ビューアと食い違うことが起こります。

そこまでひどく食い違うことはないので、仕方がないと割り切るしかなさそうです。

**Comment by kuina** [comment]
修正をpushしました。
結構仕組みを大胆に変えてしまったので、念のためTattちゃんに動作を確認して頂けたらと思っています。

**Comment by tatt61880** [comment]
修正ありがとうございます！
問題ないように思います。

修正前後で、主に口や眉や頬の表示に改善が見られました。:-)
ビフォーアフターの比較画像: http://tatt.ch/kuin/bugs/20180107/before_after.png
ソースコード: http://tatt.ch/kuin/bugs/20180107/test.kn
(参考画像: https://twitter.com/kazamidori_k/status/949158718389669889 )

draw@makeFontの引数の削除に関しても特に問題は見られませんでした。
引数が減って良かったと思います。:-)

**Comment by kuina** [comment]
Tattちゃん、ご確認ありがとうございました！
クローズします。
