### ISSUE TITLE
switchにおけるcase毎のスコープ

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#78]
下記のコードがコンパイルエラー( `EP0005: 同一スコープ内に同じ識別子「x」が存在します。` )になります。
```
func main()
	switch(1)
	case 1
		var x: int
	case 2
		var x: int
	end switch
end func
```

下記のように、blockでくくるとコンパイルできます。
```
func main()
	switch(1)
	case 1
		block
			var x: int
		end block
	case 2
		block
			var x: int
		end block
	end switch
end func
```

Kuinではswitch文でフォールスルーする書き方はできないので、blockで明示的に括らなくても、case毎に変数のスコープを分けるのが良いと思います。

**Comment by kuina** [comment]
そうですね！ わたしもずっと直したいと思っていました。
switchだけでなく、ifにおけるelse節なども同様ですので修正します。

**Comment by kuina** [comment]
elif、else、case、default、catch、finally節をスコープに分けました。
対処としては、これらの中に自動でblock～end blockを作るような感じです。
手元で一通り動作は確認しましたが、変更が大きいためエンバグしている可能性は無きにしも非ずです。

**Comment by tatt61880** [comment]
対応ありがとうございます！
ifとelif(あるいはelse)の間の部分と、tryとcatch(あるいはfinally)の間の部分にも対応が必要そうです。
```
func main()
	for i(1, 3)
		if(i = 1)
		elif(i = 2)
			var x: int :: 2
			do cui@print("\{x}\n")
		else
			var x: int :: 0
			do cui@print("\{x}\n")
		end if
	end for
end func
```
上記のコードはコンパイル＆実行ができますが、
下記のコードはコンパイルエラー(`EP0058: 上位のスコープ内に同じ識別子「x」が存在します。`)になります。
```
func main()
	for i(1, 3)
		if(i = 1)
			var x: int :: 1
			do cui@print("\{x}\n")
		elif(i = 2)
			var x: int :: 2
			do cui@print("\{x}\n")
		else
			var x: int :: 0
			do cui@print("\{x}\n")
		end if
	end for
end func
```

**Comment by kuina** [comment]
盲点でした><

**Comment by kuina** [comment]
修正しました！

**Comment by tatt61880** [comment]
ありがとうございます！
修正されていることを確認しました。:-)
クローズします！
