### ISSUE TITLE
1行で複数の変数・定数を定義しようとするとコンパイルエラーになります。

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#8]
仕様( Kuinの変数定義: http://kuina.ch/kuin/a4 , const文: http://kuina.ch/kuin/a5 )によると、
【「,」で区切って複数の変数を定義することもできます。】とのことですが、下記のコードでコンパイルエラーになりました。
【[Error] EP0006: 文字「 」が記述されるべき箇所に、文字「,」が記述されました。】
func main()
  var a: int :: 1, b: int :: 2
  const c: int :: 1, d: int :: 2
end func

**Comment by kuina** [comment]
カンマで複数指定できる機能は、実はコードが見づらくなるという理由から見直し中でした。
もし強い要望がなければ仕様から削除したいと思います。

**Comment by kuina** [comment]
ドキュメントからカンマの記述を削除しました。
違和感がなければクローズしてくださいっ。

**Comment by tatt61880** [comment]
「カンマで複数指定できる機能」は、「あっても良いかも」という程度の認識でした。
コードが見づらくなるという理由で見直されたとのことで、納得です。
ドキュメントの変更点を確認しました。
クローズします。
