### ISSUE TITLE
float.toStrFmtが正しく動作しない

### ISSUE THREAD

**Issue by ghost** [kuina/Kuin#81]
```
func main()
	do cui@print((9.17).toStrFmt(".1f"))
end func
```
このコードで、`9.2`が出力されることを期待しましたが、出力は`(null)`でした。
最小文字数の指定を省略すると`null`になるようです。

**Comment by kuina** [comment]
調査しますっ。

**Comment by kuina** [comment]
修正しました！
ついでに、いくつかマイナーな構文を追加しました。
http://kuina.ch/kuin/b08#a56

**Comment by ghost** [comment]
ありがとうございました クローズします
