### ISSUE TITLE
【ドキュメント】dict.forEachにおけるcallbackの型

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#82]
Kuinの組み込みメソッド( http://kuina.ch/kuin/b08#a19 )の「forEachメソッドの定義」で、
`func forEach(callback: func<(キーの型, 要素の型): bool>, data: kuin@Class): bool`
と書かれています。
実際にはcallbackの引数の数は2つではなく3つで、正しくは
`func forEach(callback: func<(キーの型, 要素の型, kuin@Class): bool>, data: kuin@Class): bool`
だと思います。

**Comment by kuina** [comment]
ありがとうございます、修正しました！

**Comment by tatt61880** [comment]
ありがとうございます！
修正されたことを確認しました！クローズします！
