### ISSUE TITLE
EA0037発生時に予期せぬエラーが発生

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#84]
下記のコードをKuinエディタにコピペし、コンパイルすると「予期せぬエラーです」というメッセージが表示されます。
```
func main()
	var x: x :: 1
end func
```
※本来 `EA0037: 型を記述すべきところに型以外が記述されました。` になるコードです。

**Comment by tatt61880** [comment]
上記の問題は、2018.1.17時点のバージョンでは発生しません。
一昨日のコミット( 22aa250adfb6d0d234fd019c4a1d70a20287ab2b )が関係していると思います。

**Comment by kuina** [comment]
構文解析でエラーが出ても、意味解析を可能な限り行ってエラーを出すように変更したのですが、
入念に動作を確認したつもりでも残っていましたね><

**Comment by tatt61880** [comment]
プルリク( #87 )がマージされたことによって修正されました♪
ありがとうございます。クローズします！
