### ISSUE TITLE
名前を付けて保存時にKuin.exeが落ちる

### ISSUE THREAD

**Issue by tatt61880** [kuina/Kuin#92]
名前を付けて保存したあと、カーソル移動などの操作を行うとKuin.exeが落ちます。
保存直後には落ちないようです。

**Comment by tatt61880** [comment]
`kuin_editor/src.kn` の saveMainSrc 関数内の`do @clearDocs()`をコメントアウトしてみたところ落ちないようになりました。
これが正しい修正なのかどうか、自信はないですが…。

**Comment by kuina** [comment]
あれ…調査します><

**Comment by kuina** [comment]
修正しました。
do @clearDocs() の削除で問題ありませんでした。

**Comment by kuina** [comment]
補足すると clearDocs は文字通り、ドキュメントの終了処理を行っていますが、
new と open はともかく、save では引き続きドキュメントを使用するため解放してはいけなかったです。

**Comment by tatt61880** [comment]
修正ありがとうございます！クローズします。

**Comment by kuina** [comment]
(ついでにこっそり、2018_02_17を差し替えておきました。)
