### ISSUE TITLE
正規表現において"("や")"を間違えて指定した場合、Kuinエディタが落ちる

### ISSUE THREAD

**Issue by taraco2261** [kuina/Kuin#93]
エディタの検索や置換にて正規表現のチェックを入れた操作において、
間違えて"("か")"のどちらかのみを含んで使用した場合、
Kuinエディタ自体が強制終了します。
最新2018.2.17バージョンにて確認しました。

**Comment by kuina** [comment]
はーい！

**Comment by kuina** [comment]
2018.2.17 では確実に問題が再現して、slnから生成したKuinでも再現しましたが、
何度かslnから生成し直したら正しく動くようになりました。
一番厄介なパターンですね…><

**Comment by kuina** [comment]
修正しました。
3.17 では直っています。

**Comment by taraco2261** [comment]
ありがとうございます！
